//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_Lab_23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public System.Guid SessionID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoffTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
